<?php

namespace Database\Seeders;

use App\Models\Producto;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Limpiar catálogo previo
        Producto::query()->delete();

        $productos = [
            [
                'nombre' => 'Kattia - Tapizada',
                'descripcion' => 'Silla Dimensiones: Ancho: 55.0 cm, Alto: 90.0 cm, Profundidad: 60.0 cm. Materiales / Acabados disponibles: Tabatex Liquid Otter,  Dylan Latte,  Napoli Oxford,  Napoli Sand.',
                'precio' => 3400.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row16.png',
                'categoria' => 'Sillas y Bancos',
                'stock' => 10,
                'calificacion' => 4.5,
                'destacado' => true,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Serrano - De Madera',
                'descripcion' => 'Silla Dimensiones: Ancho: 60.0 cm, Alto: 70.0 cm, Profundidad: 50.0 cm. Materiales / Acabados disponibles: Tabatex Roma Steel, Tabatex Liquid Wood, Tabatex Dylan Cream, Tabatex Dylan Evony,  Napoli Olivo.',
                'precio' => 3650.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row17.png',
                'categoria' => 'Sillas y Bancos',
                'stock' => 11,
                'calificacion' => 4.6,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Monna - De Madera',
                'descripcion' => 'Silla Dimensiones: Ancho: 58.0 cm, Alto: 70.0 cm, Profundidad: 50.0 cm. Materiales / Acabados disponibles: Tabatex Roma Oyster, Tabatex Dylan Chocolate,  Flip Flop Silver,  Dylan Latte,  Napoli Oxford.',
                'precio' => 3900.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row18.png',
                'categoria' => 'Sillas y Bancos',
                'stock' => 12,
                'calificacion' => 4.7,
                'destacado' => false,
                'porcentaje_descuento' => 15,
                'precio_descuento' => 3315.0,
            ],
            [
                'nombre' => 'Tina - De Madera',
                'descripcion' => 'Silla Dimensiones: Ancho: 45.0 cm, Alto: 70.0 cm, Profundidad: 50.0 cm. Materiales / Acabados disponibles: Tabatex Roma Oyster, Tabatex Mondra Taupe,  Napoli Olivo, Madera de pino entonada- Blanco Medio, Madera de pino entonada- Nogal Medio 1.',
                'precio' => 4150.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row19.png',
                'categoria' => 'Sillas y Bancos',
                'stock' => 13,
                'calificacion' => 4.8,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Torento - Tapizada',
                'descripcion' => 'Silla Dimensiones: Ancho: 64.0 cm, Alto: 84.0 cm, Profundidad: 64.0 cm. Materiales / Acabados disponibles: Tabatex Roma Steel, Tabatex Dylan Chocolate,  Dylan Latte,  Napoli Marino.',
                'precio' => 4400.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row20.png',
                'categoria' => 'Sillas y Bancos',
                'stock' => 14,
                'calificacion' => 4.9,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Padua - Herrería Y Tapizado',
                'descripcion' => 'Silla Dimensiones: Ancho: 55.0 cm, Alto: 70.0 cm, Profundidad: 55.0 cm. Materiales / Acabados disponibles: Tabatex Roma Oyster, Tabatex Liquid Silver, Tabatex Dylan Evony.',
                'precio' => 4650.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row21.png',
                'categoria' => 'Sillas y Bancos',
                'stock' => 15,
                'calificacion' => 5.0,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Bimba - Tapizado',
                'descripcion' => 'Sillón Comedor Dimensiones: Ancho: 65.0 cm, Alto: 78.0 cm, Profundidad: 65.0 cm. Materiales / Acabados disponibles: Tabatex Liquid Wood, Tabatex Dylan Cream,  Napoli Oxford,  Napoli Black, Madera de pino entonada- Nogal Medio 1.',
                'precio' => 15400.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row22.png',
                'categoria' => 'Comedor',
                'stock' => 16,
                'calificacion' => 4.5,
                'destacado' => true,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Olvera - Tapizado',
                'descripcion' => 'Sillón Dimensiones: Ancho: 70.0 cm, Alto: 70.0 cm, Profundidad: 75.0 cm. Materiales / Acabados disponibles: Tabatex Germany Moka, Tabatex Germany Brick, Tabatex Germany Olive, Tabatex Mondra Coffe,  Flip Flop Silver.',
                'precio' => 8500.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row23.png',
                'categoria' => 'Salón',
                'stock' => 17,
                'calificacion' => 4.6,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Palermo - Modudlar',
                'descripcion' => 'Sofa Dimensiones: Ancho: 255.0 cm, Alto: 80.0 cm, Profundidad: 95.0 cm. Materiales / Acabados disponibles: Tabatex Roma Oyster, Tabatex Roma Steel, Tabatex Liquid Ebony.',
                'precio' => 17050.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row24.png',
                'categoria' => 'Salón',
                'stock' => 18,
                'calificacion' => 4.7,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Zenit - Tapizada',
                'descripcion' => 'Banca Dimensiones: Ancho: 142.0 cm, Alto: 44.0 cm, Profundidad: 42.0 cm. Materiales / Acabados disponibles: Tabatex Sakura Midnight, Tabatex Sakura Moleskin, Tabatex Germany Navy, Tabatex Roma Latte, Tabatex Liquid Olivo.',
                'precio' => 5700.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row25.png',
                'categoria' => 'Sillas y Bancos',
                'stock' => 19,
                'calificacion' => 4.8,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'West - Sillon Ind. Angosto',
                'descripcion' => 'Sala Modular Dimensiones: Ancho: 75.0 cm, Alto: 72.5 cm, Profundidad: 100.0 cm. Materiales / Acabados disponibles: Tabatex Liquid Silver,  Napoli Oxford,  Napoli Black.',
                'precio' => 25250.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row26.png',
                'categoria' => 'Salón',
                'stock' => 20,
                'calificacion' => 4.9,
                'destacado' => false,
                'porcentaje_descuento' => 15,
                'precio_descuento' => 21462.5,
            ],
            [
                'nombre' => 'West - Sillon Ind. Ancho',
                'descripcion' => 'Sala Modular Dimensiones: Ancho: 100.0 cm, Alto: 72.5 cm, Profundidad: 100.0 cm.',
                'precio' => 25500.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row26.png',
                'categoria' => 'Salón',
                'stock' => 21,
                'calificacion' => 5.0,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'West - Love Seat',
                'descripcion' => 'Sala Modular Dimensiones: Ancho: 125.0 cm, Alto: 72.5 cm, Profundidad: 100.0 cm.',
                'precio' => 25750.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row26.png',
                'categoria' => 'Salón',
                'stock' => 22,
                'calificacion' => 4.5,
                'destacado' => true,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'West - Chaice',
                'descripcion' => 'Sala Modular Dimensiones: Ancho: 100.0 cm, Alto: 72.5 cm, Profundidad: 145.0 cm.',
                'precio' => 26000.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row26.png',
                'categoria' => 'Salón',
                'stock' => 23,
                'calificacion' => 4.6,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'West - Esquinero',
                'descripcion' => 'Sala Modular Dimensiones: Ancho: 100.0 cm, Alto: 72.5 cm, Profundidad: 100.0 cm.',
                'precio' => 24500.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row26.png',
                'categoria' => 'Salón',
                'stock' => 24,
                'calificacion' => 4.7,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'West - Taburete Cuadrado Grande',
                'descripcion' => 'Sala Modular Dimensiones: Ancho: 100.0 cm, Alto: 42.5 cm, Profundidad: 100.0 cm.',
                'precio' => 4050.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row26.png',
                'categoria' => 'Sillas y Bancos',
                'stock' => 10,
                'calificacion' => 4.8,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'West - Taburete Rectangular Grande',
                'descripcion' => 'Sala Modular Dimensiones: Ancho: 50.0 cm, Alto: 42.5 cm, Profundidad: 100.0 cm.',
                'precio' => 4300.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row26.png',
                'categoria' => 'Sillas y Bancos',
                'stock' => 11,
                'calificacion' => 4.9,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'West - Taburete Cuadrado Mediano',
                'descripcion' => 'Sala Modular Dimensiones: Ancho: 75.0 cm, Alto: 42.5 cm, Profundidad: 75.0 cm.',
                'precio' => 4550.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row26.png',
                'categoria' => 'Sillas y Bancos',
                'stock' => 12,
                'calificacion' => 5.0,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'West - Brazos',
                'descripcion' => 'Sala Modular Dimensiones: Ancho: 25.0 cm, Alto: 60.0 cm, Profundidad: 80.0 cm.',
                'precio' => 25500.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row26.png',
                'categoria' => 'Salón',
                'stock' => 13,
                'calificacion' => 4.5,
                'destacado' => true,
                'porcentaje_descuento' => 15,
                'precio_descuento' => 21675.0,
            ],
            [
                'nombre' => 'Virgo - Taburete Cuadrado',
                'descripcion' => 'Sala Modular Dimensiones: Ancho: 100.0 cm, Alto: 45.0 cm, Profundidad: 100.0 cm. Materiales / Acabados disponibles: Tabatex Roma Latte, Tabatex Roma Steel, Tabatex Liquid Silver, Tabatex Liquid Beige, Tabatex Liquid Navy.',
                'precio' => 5050.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row35.png',
                'categoria' => 'Sillas y Bancos',
                'stock' => 14,
                'calificacion' => 4.6,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Virgo - Taburete Rectangular',
                'descripcion' => 'Sala Modular Dimensiones: Ancho: 180.0 cm, Alto: 45.0 cm, Profundidad: 100.0 cm.',
                'precio' => 5300.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row35.png',
                'categoria' => 'Sillas y Bancos',
                'stock' => 15,
                'calificacion' => 4.7,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Virgo - Esquinero',
                'descripcion' => 'Sala Modular Dimensiones: Ancho: 135.0 cm, Alto: 45.0 cm, Profundidad: 135.0 cm.',
                'precio' => 24500.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row35.png',
                'categoria' => 'Salón',
                'stock' => 16,
                'calificacion' => 4.8,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Virgo - Respaldo',
                'descripcion' => 'Sala Modular Dimensiones: Ancho: 80.0 cm, Alto: 35.0 cm, Profundidad: 35.0 cm.',
                'precio' => 24750.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row35.png',
                'categoria' => 'Salón',
                'stock' => 17,
                'calificacion' => 4.9,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Lucier - Tapizada',
                'descripcion' => 'Recamara Dimensiones: Ancho: 214.0 cm, Alto: 110.0 cm, Profundidad: 210.0 cm. Materiales / Acabados disponibles: Tabatex Dylan Chocolate,  Napoli Oxford,  Napoli Sand.',
                'precio' => 22400.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row39.png',
                'categoria' => 'Dormitorio',
                'stock' => 18,
                'calificacion' => 5.0,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Aura - Tapizada',
                'descripcion' => 'Recamara Dimensiones: Ancho: 230.0 cm, Alto: 130.0 cm, Profundidad: 218.0 cm. Materiales / Acabados disponibles: Tabatex Germany Ivory, Tabatex Germany Navy, Tabatex Germany Olive, Tabatex Liquid Wood, Tabatex Liquid Rose.',
                'precio' => 22650.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row40.png',
                'categoria' => 'Dormitorio',
                'stock' => 19,
                'calificacion' => 4.5,
                'destacado' => true,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Isabella - Tapizada',
                'descripcion' => 'Recamara Dimensiones: Ancho: 214.0 cm, Alto: 110.0 cm, Profundidad: 210.0 cm. Materiales / Acabados disponibles: Tabatex Liquid Silver, Tabatex Liquid Beige, Tabatex Mondra Taupe.',
                'precio' => 22900.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row41.png',
                'categoria' => 'Dormitorio',
                'stock' => 20,
                'calificacion' => 4.6,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Duna - Tapizada',
                'descripcion' => 'Recamara Dimensiones: Ancho: 214.0 cm, Alto: 110.0 cm, Profundidad: 210.0 cm. Materiales / Acabados disponibles: Tabatex Liquid Wood, Tabatex Liquid Olivo, Tabatex Napoli Marino, Tabatex Liquid Otter.',
                'precio' => 23150.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row42.png',
                'categoria' => 'Dormitorio',
                'stock' => 21,
                'calificacion' => 4.7,
                'destacado' => false,
                'porcentaje_descuento' => 15,
                'precio_descuento' => 19677.5,
            ],
            [
                'nombre' => 'Luna - Tapizada',
                'descripcion' => 'Recamara Dimensiones: Ancho: 214.0 cm, Alto: 110.0 cm, Profundidad: 210.0 cm. Materiales / Acabados disponibles: Tabatex Germany Ivory, Tabatex Germany Olive, Tabatex Liquid Otter, Tabatex Mondra Coffe.',
                'precio' => 23400.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row43.png',
                'categoria' => 'Dormitorio',
                'stock' => 22,
                'calificacion' => 4.8,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Pistacho - Tapizada',
                'descripcion' => 'Cama Dimensiones: Ancho: 214.0 cm, Alto: 120.0 cm, Profundidad: 220.0 cm. Materiales / Acabados disponibles: Tabatex Sakura Moleskin, Tabatex Germany Brick,  Flip Flop Silver,  Napoli Sand.',
                'precio' => 13500.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row44.png',
                'categoria' => 'Dormitorio',
                'stock' => 23,
                'calificacion' => 4.9,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Molina - Madera Sólida',
                'descripcion' => 'Cama Dimensiones: Ancho: 190.0 cm, Alto: 87.0 cm, Profundidad: 210.0 cm. Materiales / Acabados disponibles: Madera de pino entonada- Nogal Medio 1, Madera de pino entonada- Nogal Oscuro.',
                'precio' => 13750.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row45.png',
                'categoria' => 'Dormitorio',
                'stock' => 24,
                'calificacion' => 5.0,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Patricio - Tapizado',
                'descripcion' => 'Taburete Dimensiones: Ancho: 67.0 cm, Alto: 51.5 cm, Profundidad: 58.0 cm. Materiales / Acabados disponibles: Tabatex Sakura Steel, Tabatex Germany Moka, Tabatex Mondra Coffe,  Flip Flop Latte,  Napoli Olivo.',
                'precio' => 4300.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row46.png',
                'categoria' => 'Sillas y Bancos',
                'stock' => 10,
                'calificacion' => 4.5,
                'destacado' => true,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Torres - Asiento Tapizado Base Madera',
                'descripcion' => 'Taburete Dimensiones: Ancho: 55.0 cm, Alto: 50.0 cm, Profundidad: 55.0 cm. Materiales / Acabados disponibles: Tabatex Sakura Midnight, Tabatex Germany Brick, Tabatex Liquid Ebony,  Flip Flop Latte,  Napoli Marino.',
                'precio' => 4550.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row47.png',
                'categoria' => 'Sillas y Bancos',
                'stock' => 11,
                'calificacion' => 4.6,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Del Rio - Tapizado Base Madera',
                'descripcion' => 'Taburete Dimensiones: Ancho: 45.0 cm, Alto: 50.0 cm, Profundidad: 45.0 cm. Materiales / Acabados disponibles: Tabatex Germany Silver, Tabatex Germany Moka, Tabatex Germany Olive,  Flip Flop Latte, Madera de pino entonada- Blanco Medio.',
                'precio' => 4800.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row48.png',
                'categoria' => 'Sillas y Bancos',
                'stock' => 12,
                'calificacion' => 4.7,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Del Rio',
                'descripcion' => 'Taburete Dimensiones: Ancho: ↔ (Ancho) cm, Alto: ↕ (Altura) cm, Profundidad: ↗ (Prof) cm. Materiales / Acabados disponibles: MATERIAL 2, MATERIAL 3, MATERIAL 4, MATERIAL 5, MATERIAL 6.',
                'precio' => 5050.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row48.png',
                'categoria' => 'Sillas y Bancos',
                'stock' => 13,
                'calificacion' => 4.8,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Risotto - Melamina',
                'descripcion' => 'Buró Dimensiones: Ancho: 55.0 cm, Alto: 45.0 cm, Profundidad: 45.0 cm. Materiales / Acabados disponibles: Melamina Arauco Copal, Melamina Arauco Malta, Melamina Arauco Durango, Melamina Arauco Wengué.',
                'precio' => 6300.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row51.png',
                'categoria' => 'Dormitorio',
                'stock' => 14,
                'calificacion' => 4.9,
                'destacado' => false,
                'porcentaje_descuento' => 15,
                'precio_descuento' => 5355.0,
            ],
            [
                'nombre' => 'Risotto - Con Cubierta De Mármol',
                'descripcion' => 'Buró Dimensiones: Ancho: 55.0 cm, Alto: 45.0 cm, Profundidad: 45.0 cm. Materiales / Acabados disponibles: Melamina Arauco Copal, Melamina Arauco Malta, Melamina Arauco Durango, Melamina Arauco Wengué, Mármol Travertino Blanco.',
                'precio' => 4800.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row52.png',
                'categoria' => 'Dormitorio',
                'stock' => 15,
                'calificacion' => 5.0,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Domingo - Melamina',
                'descripcion' => 'Buró Dimensiones: Ancho: 45.0 cm, Alto: 50.0 cm, Profundidad: 40.0 cm. Materiales / Acabados disponibles: Melamina Arauco Copal, Melamina Arauco Malta, Melamina Arauco Durango, Melamina Arauco Wengué.',
                'precio' => 5050.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row53.png',
                'categoria' => 'Dormitorio',
                'stock' => 16,
                'calificacion' => 4.5,
                'destacado' => true,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Noruega - Mármol',
                'descripcion' => 'Buró Dimensiones: Ancho: 45.0 cm, Alto: 50.0 cm, Profundidad: 45.0 cm. Materiales / Acabados disponibles: Mármol Travertino Blanco, Mármol Querétaro Negro, Mármol Carrara, Pdte. cotización.',
                'precio' => 5300.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row54.png',
                'categoria' => 'Dormitorio',
                'stock' => 17,
                'calificacion' => 4.6,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Suecia - Mármol',
                'descripcion' => 'Buró Dimensiones: Ancho: 45.0 cm, Alto: 50.0 cm, Profundidad: 45.0 cm. Materiales / Acabados disponibles: Mármol Travertino Blanco, Mármol Querétaro Negro, Mármol Carrara, Pdte. cotización.',
                'precio' => 5550.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row55.png',
                'categoria' => 'Dormitorio',
                'stock' => 18,
                'calificacion' => 4.7,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Romina - Mármol',
                'descripcion' => 'Recibidor Dimensiones: Ancho: 80.0 cm, Alto: 85.0 cm, Profundidad: 25.0 cm. Materiales / Acabados disponibles: Mármol Travertino Blanco, Mármol Querétaro Negro, Mármol Carrara, Pdte. cotización.',
                'precio' => 9900.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row56.png',
                'categoria' => 'Muebles Auxiliares',
                'stock' => 19,
                'calificacion' => 4.8,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Julia - Pedestal',
                'descripcion' => 'Buró/Mesa auxiliar Dimensiones: Ancho: 40.0 cm, Alto: 55.0 cm, Profundidad: 40.0 cm. Materiales / Acabados disponibles: Mármol Travertino Blanco, Mármol Querétaro Negro, Mármol Carrara, Pdte. cotización.',
                'precio' => 15150.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row57.png',
                'categoria' => 'Comedor',
                'stock' => 20,
                'calificacion' => 4.9,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Pino - Pedestal',
                'descripcion' => 'Mesa de comedor Materiales / Acabados disponibles: Pdte. cotización cubierta.',
                'precio' => 15400.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row58.png',
                'categoria' => 'Comedor',
                'stock' => 21,
                'calificacion' => 5.0,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Diandra - Pedestal',
                'descripcion' => 'Mesa de comedor.',
                'precio' => 13900.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row59.png',
                'categoria' => 'Comedor',
                'stock' => 22,
                'calificacion' => 4.5,
                'destacado' => true,
                'porcentaje_descuento' => 15,
                'precio_descuento' => 11815.0,
            ],
            [
                'nombre' => 'Nina - Pedestal',
                'descripcion' => 'Mesa de comedor.',
                'precio' => 14150.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row60.png',
                'categoria' => 'Comedor',
                'stock' => 23,
                'calificacion' => 4.6,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Otoño - Pedestal',
                'descripcion' => 'Mesa de comedor.',
                'precio' => 14400.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row61.png',
                'categoria' => 'Comedor',
                'stock' => 24,
                'calificacion' => 4.7,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Romero - Pedestal',
                'descripcion' => 'Mesa de comedor.',
                'precio' => 14650.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row62.png',
                'categoria' => 'Comedor',
                'stock' => 10,
                'calificacion' => 4.8,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Carol - Pedestal',
                'descripcion' => 'Mesa de comedor.',
                'precio' => 14900.0,
                'imagen_url' => '/storage/productos/mueble_tapi_row63.png',
                'categoria' => 'Comedor',
                'stock' => 11,
                'calificacion' => 4.9,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Sao Paulo - Cubierta Redonda 4 Personas',
                'descripcion' => 'Mesa de comedor.',
                'precio' => 12450.0,
                'imagen_url' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=800',
                'categoria' => 'Comedor',
                'stock' => 12,
                'calificacion' => 5.0,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Sao Paulo - Cubierta Redonda 6 Personas',
                'descripcion' => 'Mesa de comedor.',
                'precio' => 16000.0,
                'imagen_url' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=800',
                'categoria' => 'Comedor',
                'stock' => 13,
                'calificacion' => 4.5,
                'destacado' => true,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Sao Paulo - Cubierta Redonda 8 Personas',
                'descripcion' => 'Mesa de comedor.',
                'precio' => 18900.0,
                'imagen_url' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=800',
                'categoria' => 'Comedor',
                'stock' => 14,
                'calificacion' => 4.6,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Atenas - Cubierta Cuadrada 4 Personas',
                'descripcion' => 'Mesa de comedor.',
                'precio' => 11450.0,
                'imagen_url' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=800',
                'categoria' => 'Comedor',
                'stock' => 15,
                'calificacion' => 4.7,
                'destacado' => false,
                'porcentaje_descuento' => 15,
                'precio_descuento' => 9732.5,
            ],
            [
                'nombre' => 'Atenas - Cubierta Cuadrada 8 Personas',
                'descripcion' => 'Mesa de comedor.',
                'precio' => 19400.0,
                'imagen_url' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=800',
                'categoria' => 'Comedor',
                'stock' => 16,
                'calificacion' => 4.8,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Santiago - Cubierta Rectangular 6 Personas',
                'descripcion' => 'Mesa de comedor.',
                'precio' => 15250.0,
                'imagen_url' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=800',
                'categoria' => 'Comedor',
                'stock' => 17,
                'calificacion' => 4.9,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Santiago - Cubierta Rectangular 8 Personas',
                'descripcion' => 'Mesa de comedor.',
                'precio' => 19900.0,
                'imagen_url' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=800',
                'categoria' => 'Comedor',
                'stock' => 18,
                'calificacion' => 5.0,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Oslo',
                'descripcion' => 'Mesa de comedor.',
                'precio' => 15150.0,
                'imagen_url' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=800',
                'categoria' => 'Comedor',
                'stock' => 19,
                'calificacion' => 4.5,
                'destacado' => true,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Budapest',
                'descripcion' => 'Mesa de comedor.',
                'precio' => 15400.0,
                'imagen_url' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=800',
                'categoria' => 'Comedor',
                'stock' => 20,
                'calificacion' => 4.6,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Budapest',
                'descripcion' => 'Mesa de comedor.',
                'precio' => 13900.0,
                'imagen_url' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=800',
                'categoria' => 'Comedor',
                'stock' => 21,
                'calificacion' => 4.7,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Budapest',
                'descripcion' => 'Mesa de comedor.',
                'precio' => 14150.0,
                'imagen_url' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=800',
                'categoria' => 'Comedor',
                'stock' => 22,
                'calificacion' => 4.8,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Budapest',
                'descripcion' => 'Mesa de comedor.',
                'precio' => 14400.0,
                'imagen_url' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=800',
                'categoria' => 'Comedor',
                'stock' => 23,
                'calificacion' => 4.9,
                'destacado' => false,
                'porcentaje_descuento' => 15,
                'precio_descuento' => 12240.0,
            ],
            [
                'nombre' => 'Budapest',
                'descripcion' => 'Mesa de comedor.',
                'precio' => 14650.0,
                'imagen_url' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=800',
                'categoria' => 'Comedor',
                'stock' => 24,
                'calificacion' => 5.0,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Budapest',
                'descripcion' => 'Mesa de comedor.',
                'precio' => 14900.0,
                'imagen_url' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=800',
                'categoria' => 'Comedor',
                'stock' => 10,
                'calificacion' => 4.5,
                'destacado' => true,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Budapest',
                'descripcion' => 'Mesa de comedor.',
                'precio' => 15150.0,
                'imagen_url' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=800',
                'categoria' => 'Comedor',
                'stock' => 11,
                'calificacion' => 4.6,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Budapest',
                'descripcion' => 'Mesa de comedor.',
                'precio' => 15400.0,
                'imagen_url' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=800',
                'categoria' => 'Comedor',
                'stock' => 12,
                'calificacion' => 4.7,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Budapest',
                'descripcion' => 'Mesa de comedor.',
                'precio' => 13900.0,
                'imagen_url' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=800',
                'categoria' => 'Comedor',
                'stock' => 13,
                'calificacion' => 4.8,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Budapest',
                'descripcion' => 'Mesa de comedor.',
                'precio' => 14150.0,
                'imagen_url' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=800',
                'categoria' => 'Comedor',
                'stock' => 14,
                'calificacion' => 4.9,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Budapest',
                'descripcion' => 'Mesa de comedor.',
                'precio' => 14400.0,
                'imagen_url' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=800',
                'categoria' => 'Comedor',
                'stock' => 15,
                'calificacion' => 5.0,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Budapest',
                'descripcion' => 'Mesa de comedor.',
                'precio' => 14650.0,
                'imagen_url' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=800',
                'categoria' => 'Comedor',
                'stock' => 16,
                'calificacion' => 4.5,
                'destacado' => true,
                'porcentaje_descuento' => 15,
                'precio_descuento' => 12452.5,
            ],
            [
                'nombre' => 'Budapest',
                'descripcion' => 'Mesa de comedor.',
                'precio' => 14900.0,
                'imagen_url' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=800',
                'categoria' => 'Comedor',
                'stock' => 17,
                'calificacion' => 4.6,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Budapest',
                'descripcion' => 'Mesa de comedor.',
                'precio' => 15150.0,
                'imagen_url' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=800',
                'categoria' => 'Comedor',
                'stock' => 18,
                'calificacion' => 4.7,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Tokio',
                'descripcion' => 'Mesa de comedor.',
                'precio' => 15400.0,
                'imagen_url' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=800',
                'categoria' => 'Comedor',
                'stock' => 19,
                'calificacion' => 4.8,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Denver',
                'descripcion' => 'Mesa de comedor.',
                'precio' => 13900.0,
                'imagen_url' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=800',
                'categoria' => 'Comedor',
                'stock' => 20,
                'calificacion' => 4.9,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Moscou',
                'descripcion' => 'Mesa de comedor.',
                'precio' => 14150.0,
                'imagen_url' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=800',
                'categoria' => 'Comedor',
                'stock' => 21,
                'calificacion' => 5.0,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Milán',
                'descripcion' => 'Mesa de comedor.',
                'precio' => 14400.0,
                'imagen_url' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=800',
                'categoria' => 'Comedor',
                'stock' => 22,
                'calificacion' => 4.5,
                'destacado' => true,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Nápoles',
                'descripcion' => 'Mesa de comedor.',
                'precio' => 14650.0,
                'imagen_url' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=800',
                'categoria' => 'Comedor',
                'stock' => 23,
                'calificacion' => 4.6,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Lisboa',
                'descripcion' => 'Mesa de comedor.',
                'precio' => 14900.0,
                'imagen_url' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=800',
                'categoria' => 'Comedor',
                'stock' => 24,
                'calificacion' => 4.7,
                'destacado' => false,
                'porcentaje_descuento' => 15,
                'precio_descuento' => 12665.0,
            ],
            [
                'nombre' => 'Turín',
                'descripcion' => 'Mesa de comedor.',
                'precio' => 15150.0,
                'imagen_url' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=800',
                'categoria' => 'Comedor',
                'stock' => 10,
                'calificacion' => 4.8,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Osaka',
                'descripcion' => 'Mesa de comedor.',
                'precio' => 15400.0,
                'imagen_url' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=800',
                'categoria' => 'Comedor',
                'stock' => 11,
                'calificacion' => 4.9,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Moringo',
                'descripcion' => 'Mesa de comedor.',
                'precio' => 13900.0,
                'imagen_url' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=800',
                'categoria' => 'Comedor',
                'stock' => 12,
                'calificacion' => 5.0,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Berlín',
                'descripcion' => 'Mesa de comedor.',
                'precio' => 14150.0,
                'imagen_url' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=800',
                'categoria' => 'Comedor',
                'stock' => 13,
                'calificacion' => 4.5,
                'destacado' => true,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Sillón',
                'descripcion' => 'Sillón Dimensiones: Ancho: 55.0 cm, Alto: 90.0 cm, Profundidad: 60.0 cm. Materiales / Acabados disponibles: Tabatex Liquid Otter,  Dylan Latte,  Napoli Oxford,  Napoli Sand.',
                'precio' => 9000.0,
                'imagen_url' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=800',
                'categoria' => 'Salón',
                'stock' => 14,
                'calificacion' => 4.6,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Lucca - Sofá',
                'descripcion' => 'Fabricado en madera estufada de Pino, forrada de hule espuma de alta densidad y textil pendiente por definir. Dimensiones: Ancho: 199.0 cm, Alto: 88.0 cm, Profundidad: 167.0 cm. Materiales / Acabados disponibles: Tabatex Roma Steel, Tabatex Liquid Beige, Tabatex Liquid Ebony.',
                'precio' => 17550.0,
                'imagen_url' => '/storage/productos/mueble_sama_row16.jpg',
                'categoria' => 'Salón',
                'stock' => 15,
                'calificacion' => 4.7,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Cataluña - Sofá',
                'descripcion' => 'Fabricado en madera estufada de Pino, forrada de hule espuma de alta densidad y textil pendiente por definir. Dimensiones: Ancho: 237.0 cm, Alto: 97.0 cm, Profundidad: 93.0 cm. Materiales / Acabados disponibles:  Napoli Oxford,  Napoli Sand,  Napoli Marino,  Napoli Black.',
                'precio' => 17800.0,
                'imagen_url' => '/storage/productos/mueble_sama_row17.png',
                'categoria' => 'Salón',
                'stock' => 16,
                'calificacion' => 4.8,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Cataluña - Loveseat',
                'descripcion' => 'Fabricado en madera estufada de Pino, forrada de hule espuma de alta densidad y textil pendiente por definir. Dimensiones: Ancho: 180.0 cm, Alto: 97.0 cm, Profundidad: 93.0 cm.',
                'precio' => 14150.0,
                'imagen_url' => '/storage/productos/mueble_sama_row17.png',
                'categoria' => 'Salón',
                'stock' => 17,
                'calificacion' => 4.9,
                'destacado' => false,
                'porcentaje_descuento' => 15,
                'precio_descuento' => 12027.5,
            ],
            [
                'nombre' => 'Cataluña - Sillón',
                'descripcion' => 'Fabricado en madera estufada de Pino, forrada de hule espuma de alta densidad y textil pendiente por definir. Dimensiones: Ancho: 130.0 cm, Alto: 97.0 cm, Profundidad: 93.0 cm.',
                'precio' => 10000.0,
                'imagen_url' => '/storage/productos/mueble_sama_row17.png',
                'categoria' => 'Salón',
                'stock' => 18,
                'calificacion' => 5.0,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Samoa - Esquinero',
                'descripcion' => 'Fabricado en madera estufada de Pino, forrada de hule espuma de alta densidad y textil pendiente por definir. Dimensiones: Ancho: 90.0 cm, Alto: 75.0 cm, Profundidad: 90.0 cm. Materiales / Acabados disponibles:  Napoli Oxford,  Napoli Sand,  Napoli Marino,  Napoli Black.',
                'precio' => 24500.0,
                'imagen_url' => '/storage/productos/mueble_sama_row20.jpg',
                'categoria' => 'Salón',
                'stock' => 19,
                'calificacion' => 4.5,
                'destacado' => true,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Samoa - Sillón',
                'descripcion' => 'Fabricado en madera estufada de Pino, forrada de hule espuma de alta densidad y textil pendiente por definir. Dimensiones: Ancho: 90.0 cm, Alto: 73.0 cm, Profundidad: 90.0 cm.',
                'precio' => 8750.0,
                'imagen_url' => '/storage/productos/mueble_sama_row20.jpg',
                'categoria' => 'Salón',
                'stock' => 20,
                'calificacion' => 4.6,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Samoa - Taburete',
                'descripcion' => 'Fabricado en madera estufada de Pino, forrada de hule espuma de alta densidad y textil pendiente por definir. Dimensiones: Ancho: 90.0 cm, Alto: 45.0 cm, Profundidad: 90.0 cm.',
                'precio' => 4300.0,
                'imagen_url' => '/storage/productos/mueble_sama_row20.jpg',
                'categoria' => 'Sillas y Bancos',
                'stock' => 21,
                'calificacion' => 4.7,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Trevere - Loveseat',
                'descripcion' => 'Fabricado en madera estufada de Pino, forrada de hule espuma de alta densidad y textil pendiente por definir. Dimensiones: Ancho: 195.0 cm, Alto: 97.0 cm, Profundidad: 93.0 cm. Materiales / Acabados disponibles: Tabatex Dylan Chocolate, Tabatex Dylan Evony,  Napoli Sand,  Napoli Black.',
                'precio' => 13650.0,
                'imagen_url' => '/storage/productos/mueble_sama_row23.jpg',
                'categoria' => 'Salón',
                'stock' => 22,
                'calificacion' => 4.8,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Sala Modular Fernanda',
                'descripcion' => 'Fabricado en madera estufada de Pino, forrada de hule espuma de alta densidad y textil pendiente por definir. Dimensiones: Ancho: CHAISE  : 85  CM X 80 CM X  160  CM                   LOVESEAT: 170 CM X  80 CM X 85 CM            ESQUINERO : 85 CM X 80CM  X 85  CM   TABURETE 75 CM X 45CM X 85 CM cm.',
                'precio' => 15500.0,
                'imagen_url' => '/storage/productos/mueble_sama_row24.jpg',
                'categoria' => 'Salón',
                'stock' => 23,
                'calificacion' => 4.9,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Edimburgo - Loveseat',
                'descripcion' => 'Sala modular reclinable fabricado en madera estufada de Pino, forrada de hule espuma de alta densidad y textil pendiente por definir. Dimensiones: Ancho: 135.0 cm, Alto: 90.0 cm, Profundidad: 87.0 cm. Materiales / Acabados disponibles: Tabatex Dylan Chocolate, Tabatex Dylan Evony,  Napoli Sand,  Napoli Black.',
                'precio' => 25750.0,
                'imagen_url' => '/storage/productos/mueble_sama_row25.jpg',
                'categoria' => 'Salón',
                'stock' => 24,
                'calificacion' => 5.0,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Edimburgo - Esquinero',
                'descripcion' => 'Sala modular reclinable fabricado en madera estufada de Pino, forrada de hule espuma de alta densidad y textil pendiente por definir. Dimensiones: Ancho: 104.0 cm, Alto: 90.0 cm, Profundidad: 87.0 cm.',
                'precio' => 26000.0,
                'imagen_url' => '/storage/productos/mueble_sama_row25.jpg',
                'categoria' => 'Salón',
                'stock' => 10,
                'calificacion' => 4.5,
                'destacado' => true,
                'porcentaje_descuento' => 15,
                'precio_descuento' => 22100.0,
            ],
            [
                'nombre' => 'Edimburgo - Baúl',
                'descripcion' => 'Sala modular reclinable fabricado en madera estufada de Pino, forrada de hule espuma de alta densidad y textil pendiente por definir. Dimensiones: Ancho: 91.0 cm, Alto: 45.0 cm, Profundidad: 90.0 cm.',
                'precio' => 24500.0,
                'imagen_url' => '/storage/productos/mueble_sama_row25.jpg',
                'categoria' => 'Salón',
                'stock' => 11,
                'calificacion' => 4.6,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Milán - Sofá',
                'descripcion' => 'Fabricado en madera estufada de Pino, forrada de hule espuma de alta densidad y textil pendiente por definir. Dimensiones: Ancho: 220.0 cm, Alto: 100.0 cm, Profundidad: 70.0 cm. Materiales / Acabados disponibles: Tabatex Germany Silver, Tabatex Roma Oyster, Tabatex Liquid Wood, Tabatex Liquid Olivo,  Napoli Oxford.',
                'precio' => 17050.0,
                'imagen_url' => '/storage/productos/mueble_sama_row28.jpg',
                'categoria' => 'Salón',
                'stock' => 12,
                'calificacion' => 4.7,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Sillon Morrocoy - Sillón',
                'descripcion' => 'Fabricado en madera estufada de Pino, forrada de hule espuma de alta densidad y textil pendiente por definir. Dimensiones: Ancho: 85.0 cm, Alto: 83.0 cm, Profundidad: 83.0 cm. Materiales / Acabados disponibles: Tabatex Germany Silver, Tabatex Roma Oyster, Tabatex Liquid Wood, Tabatex Liquid Olivo,  Napoli Oxford.',
                'precio' => 9000.0,
                'imagen_url' => '/storage/productos/mueble_sama_row29.png',
                'categoria' => 'Salón',
                'stock' => 13,
                'calificacion' => 4.8,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Sala Venecia - Loveseat',
                'descripcion' => 'Fabricado en madera estufada de Pino, forrada de hule espuma de alta densidad y textil pendiente por definir. Dimensiones: Ancho: 168.0 cm, Alto: 92.0 cm, Profundidad: 83.0 cm. Materiales / Acabados disponibles: Tabatex Dylan Cream, Tabatex Dylan Chocolate, Tabatex Dylan Evony.',
                'precio' => 13650.0,
                'imagen_url' => '/storage/productos/mueble_sama_row30.png',
                'categoria' => 'Salón',
                'stock' => 14,
                'calificacion' => 4.9,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Sala Venecia - Sillón',
                'descripcion' => 'Fabricado en madera estufada de Pino, forrada de hule espuma de alta densidad y textil pendiente por definir. Dimensiones: Ancho: 120.0 cm, Alto: 92.0 cm, Profundidad: 83.0 cm.',
                'precio' => 9500.0,
                'imagen_url' => '/storage/productos/mueble_sama_row30.png',
                'categoria' => 'Salón',
                'stock' => 15,
                'calificacion' => 5.0,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Sala Venecia - Sofá',
                'descripcion' => 'Fabricado en madera estufada de Pino, forrada de hule espuma de alta densidad y textil pendiente por definir. Dimensiones: Ancho: 220.0 cm, Alto: 92.0 cm, Profundidad: 83.0 cm.',
                'precio' => 18050.0,
                'imagen_url' => '/storage/productos/mueble_sama_row30.png',
                'categoria' => 'Salón',
                'stock' => 16,
                'calificacion' => 4.5,
                'destacado' => true,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Sala Concherto - Loveseat',
                'descripcion' => 'Fabricado en madera estufada de Pino, forrada de hule espuma de alta densidad y textil pendiente por definir. Dimensiones: Ancho: 180.0 cm, Alto: 102.0 cm, Profundidad: 90.0 cm. Materiales / Acabados disponibles: Tabatex Dylan Cream, Tabatex Dylan Chocolate, Tabatex Dylan Evony.',
                'precio' => 14400.0,
                'imagen_url' => '/storage/productos/mueble_sama_row33.png',
                'categoria' => 'Salón',
                'stock' => 17,
                'calificacion' => 4.6,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Sala Concherto - Sillón',
                'descripcion' => 'Fabricado en madera estufada de Pino, forrada de hule espuma de alta densidad y textil pendiente por definir. Dimensiones: Ancho: 125.0 cm, Alto: 102.0 cm, Profundidad: 90.0 cm.',
                'precio' => 8500.0,
                'imagen_url' => '/storage/productos/mueble_sama_row33.png',
                'categoria' => 'Salón',
                'stock' => 18,
                'calificacion' => 4.7,
                'destacado' => false,
                'porcentaje_descuento' => 15,
                'precio_descuento' => 7225.0,
            ],
            [
                'nombre' => 'Sala Concherto - Sofá',
                'descripcion' => 'Fabricado en madera estufada de Pino, forrada de hule espuma de alta densidad y textil pendiente por definir. Dimensiones: Ancho: 240.0 cm, Alto: 102.0 cm, Profundidad: 90.0 cm.',
                'precio' => 17050.0,
                'imagen_url' => '/storage/productos/mueble_sama_row33.png',
                'categoria' => 'Salón',
                'stock' => 19,
                'calificacion' => 4.8,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Yorkshire - Sofa',
                'descripcion' => 'Sillón reclinable fabricado en madera estufada de Pino, forrada de hule espuma de alta densidad y textil pendiente por definir. Dimensiones: Ancho: 218.0 cm, Alto: 97.0 cm, Profundidad: 93.0 cm. Materiales / Acabados disponibles: Tabatex Dylan Cream, Tabatex Dylan Chocolate, Tabatex Dylan Evony,  Napoli Black.',
                'precio' => 17300.0,
                'imagen_url' => '/storage/productos/mueble_sama_row36.png',
                'categoria' => 'Salón',
                'stock' => 20,
                'calificacion' => 4.9,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Yorkshire - Loveseat',
                'descripcion' => 'Sillón reclinable fabricado en madera estufada de Pino, forrada de hule espuma de alta densidad y textil pendiente por definir. Dimensiones: Ancho: 167.0 cm, Alto: 97.0 cm, Profundidad: 93.0 cm.',
                'precio' => 13650.0,
                'imagen_url' => '/storage/productos/mueble_sama_row36.png',
                'categoria' => 'Salón',
                'stock' => 21,
                'calificacion' => 5.0,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Yorkshire - Sillon',
                'descripcion' => 'Sillón reclinable fabricado en madera estufada de Pino, forrada de hule espuma de alta densidad y textil pendiente por definir. Dimensiones: Ancho: 120.0 cm, Alto: 97.0 cm, Profundidad: 93.0 cm.',
                'precio' => 9500.0,
                'imagen_url' => '/storage/productos/mueble_sama_row36.png',
                'categoria' => 'Salón',
                'stock' => 22,
                'calificacion' => 4.5,
                'destacado' => true,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Bombay - Sofá Cama',
                'descripcion' => 'Sofá cama tamaño matrimonial Dimensiones: Ancho: 190.0 cm, Alto: 170.0 cm, Profundidad: 90.0 cm. Materiales / Acabados disponibles: Tabatex Germany Ivory, Tabatex Roma Steel, Tabatex Dylan Evony,  Napoli Sand,  Napoli Marino.',
                'precio' => 14750.0,
                'imagen_url' => '/storage/productos/mueble_sama_row39.png',
                'categoria' => 'Dormitorio',
                'stock' => 23,
                'calificacion' => 4.6,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Recámara Atenea',
                'descripcion' => 'Fabricado en madera estufada de Pino, forrada de hule espuma de alta densidad y textil pendiente por definir. Dimensiones: Ancho: Base: 215 CM X 30 CM  2.05CM
CABECERA : 205CM X 1.20 CM X25 CM cm.',
                'precio' => 16000.0,
                'imagen_url' => '/storage/productos/mueble_sama_row40.jpg',
                'categoria' => 'Salón',
                'stock' => 24,
                'calificacion' => 4.7,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Creta Matrimonial - Base',
                'descripcion' => 'Fabricado en madera estufada de Pino, forrada de hule espuma de alta densidad y textil pendiente por definir. Dimensiones: Ancho: 149.0 cm, Alto: 25.0 cm, Profundidad: 197.0 cm. Materiales / Acabados disponibles:  Napoli Oxford,  Napoli Sand,  Napoli Marino,  Napoli Olivo.',
                'precio' => 13500.0,
                'imagen_url' => '/storage/productos/mueble_sama_row41.jpg',
                'categoria' => 'Dormitorio',
                'stock' => 10,
                'calificacion' => 4.8,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Creta Matrimonial - Cabecera',
                'descripcion' => 'Fabricado en madera estufada de Pino, forrada de hule espuma de alta densidad y textil pendiente por definir. Dimensiones: Ancho: 145.0 cm, Alto: 120.0 cm, Profundidad: 25.0 cm.',
                'precio' => 8050.0,
                'imagen_url' => '/storage/productos/mueble_sama_row41.jpg',
                'categoria' => 'Dormitorio',
                'stock' => 11,
                'calificacion' => 4.9,
                'destacado' => false,
                'porcentaje_descuento' => 15,
                'precio_descuento' => 6842.5,
            ],
            [
                'nombre' => 'Recámara Santorini - Base',
                'descripcion' => 'Fabricado en madera estufada de Pino, forrada de hule espuma de alta densidad y textil pendiente por definir. Dimensiones: Ancho: 149.0 cm, Alto: 25.0 cm, Profundidad: 197.0 cm. Materiales / Acabados disponibles: Tabatex Sakura Midnight, Tabatex Sakura Moleskin, Tabatex Mondra Curry, Tabatex Mondra Coffe.',
                'precio' => 14000.0,
                'imagen_url' => '/storage/productos/mueble_sama_row43.jpg',
                'categoria' => 'Dormitorio',
                'stock' => 12,
                'calificacion' => 5.0,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Recámara Santorini - Cabecera',
                'descripcion' => 'Fabricado en madera estufada de Pino, forrada de hule espuma de alta densidad y textil pendiente por definir. Dimensiones: Ancho: 145.0 cm, Alto: 120.0 cm, Profundidad: 25.0 cm.',
                'precio' => 8550.0,
                'imagen_url' => '/storage/productos/mueble_sama_row43.jpg',
                'categoria' => 'Dormitorio',
                'stock' => 13,
                'calificacion' => 4.5,
                'destacado' => true,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Mikonos - Base',
                'descripcion' => 'Fabricado en madera estufada de Pino, forrada de hule espuma de alta densidad y textil pendiente por definir. Dimensiones: Ancho: 149.0 cm, Alto: 25.0 cm, Profundidad: 197.0 cm. Materiales / Acabados disponibles: Tabatex Dylan Chocolate, Tabatex Dylan Evony, Tabatex Dylan Latte.',
                'precio' => 14500.0,
                'imagen_url' => '/storage/productos/mueble_sama_row45.jpg',
                'categoria' => 'Dormitorio',
                'stock' => 14,
                'calificacion' => 4.6,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Mikonos - Cabecera',
                'descripcion' => 'Fabricado en madera estufada de Pino, forrada de hule espuma de alta densidad y textil pendiente por definir. Dimensiones: Ancho: 145.0 cm, Alto: 120.0 cm, Profundidad: 15.0 cm.',
                'precio' => 9050.0,
                'imagen_url' => '/storage/productos/mueble_sama_row45.jpg',
                'categoria' => 'Dormitorio',
                'stock' => 15,
                'calificacion' => 4.7,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Artemisa - Sofá',
                'descripcion' => 'Fabricado en madera estufada de Pino, forrada de hule espuma de alta densidad y textil  TAMPA SILVER. Dimensiones: Ancho: 190.0 cm, Alto: 83.0 cm, Profundidad: 90.0 cm. Materiales / Acabados disponibles: Tabatex Germany Ivory, Tabatex Roma Oyster, Tabatex Dylan Evony,  Napoli Black.',
                'precio' => 18300.0,
                'imagen_url' => '/storage/productos/mueble_sama_row47.jpg',
                'categoria' => 'Salón',
                'stock' => 16,
                'calificacion' => 4.8,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Marielle - Sofá',
                'descripcion' => 'Fabricado en madera estufada de Pino, forrada de hule espuma de alta densidad y textil  FRANKFURT Dimensiones: Ancho: 170.0 cm, Alto: 81.0 cm, Profundidad: 95.0 cm. Materiales / Acabados disponibles: Tabatex Germany Ivory, Tabatex Germany Navy, Tabatex Mondra Coffe, Tabatex Dylan Cream,  Napoli Oxford.',
                'precio' => 16800.0,
                'imagen_url' => '/storage/productos/mueble_sama_row48.jpg',
                'categoria' => 'Salón',
                'stock' => 17,
                'calificacion' => 4.9,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Capri Matromonial - Base',
                'descripcion' => 'Base matrimonial Capri Dimensiones: Ancho: 150.0 cm, Alto: 120.0 cm, Profundidad: 210.0 cm. Materiales / Acabados disponibles: Tabatex Sakura Moleskin, Tabatex Germany Brick,  Flip Flop Silver,  Napoli Sand.',
                'precio' => 13750.0,
                'imagen_url' => '/storage/productos/mueble_sama_row49.jpg',
                'categoria' => 'Dormitorio',
                'stock' => 18,
                'calificacion' => 5.0,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Capri Matromonial - Cabecera',
                'descripcion' => 'Base matrimonial Capri.',
                'precio' => 14000.0,
                'imagen_url' => '/storage/productos/mueble_sama_row49.jpg',
                'categoria' => 'Dormitorio',
                'stock' => 19,
                'calificacion' => 4.5,
                'destacado' => true,
                'porcentaje_descuento' => 15,
                'precio_descuento' => 11900.0,
            ],
            [
                'nombre' => 'Capri Base King Capri',
                'descripcion' => 'Base King Tipo Capri Dimensiones: Ancho: 216.0 cm, Alto: 217.0 cm, Profundidad: 210.0 cm. Materiales / Acabados disponibles: Tabatex Sakura Moleskin, Tabatex Germany Brick,  Flip Flop Silver,  Napoli Sand.',
                'precio' => 14250.0,
                'imagen_url' => '/storage/productos/mueble_sama_row51.jpg',
                'categoria' => 'Dormitorio',
                'stock' => 20,
                'calificacion' => 4.6,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
            [
                'nombre' => 'Capri Base King Capri - Cabecera',
                'descripcion' => 'Base King Tipo Capri.',
                'precio' => 14500.0,
                'imagen_url' => '/storage/productos/mueble_sama_row51.jpg',
                'categoria' => 'Dormitorio',
                'stock' => 21,
                'calificacion' => 4.7,
                'destacado' => false,
                'porcentaje_descuento' => null,
                'precio_descuento' => null,
            ],
        ];

        $slugsUsados = [];

        foreach ($productos as $item) {
            $baseSlug = Str::slug($item['nombre']);
            $slug = $baseSlug;
            $counter = 1;

            while (in_array($slug, $slugsUsados)) {
                $slug = $baseSlug. '-'. $counter;
                $counter++;
            }

            $slugsUsados[] = $slug;
            $item['slug'] = $slug;

            Producto::create($item);
        }
    }
}
